# .github/workflows/sonar.yml
name: Sonar Scan

on:
 workflow_call:

jobs:
  sonar:
    runs-on: java_build
    #needs: build  # Ensures Sonar runs after build succeeds
    steps:
      - name: SonarCloud Scan
        run: mvn sonar:sonar -Dsonar.projectKey=StephenShenk1_DevSecops_Pipeline -Dsonar.organization=stephenshenk1 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=aff0c59b-92b3-47ed-a4ce-89061dd0ea75
